using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace Primary.Rendering2.Resources
{
    public static partial class Extensions
    {
        public static bool IsTexture1DFormat(this FGTextureFormat format) => format switch
        {
            FGTextureFormat.RGBA32_Typeless => true,
            FGTextureFormat.RGBA32_Float => true,
            FGTextureFormat.RGBA32_UInt => true,
            FGTextureFormat.RGBA32_SInt => true,
            FGTextureFormat.RGB32_Typeless => true,
            FGTextureFormat.RGB32_Float => true,
            FGTextureFormat.RGB32_UInt => true,
            FGTextureFormat.RGB32_SInt => true,
            FGTextureFormat.RGBA16_Typeless => true,
            FGTextureFormat.RGBA16_Float => true,
            FGTextureFormat.RGBA16_UInt => true,
            FGTextureFormat.RGBA16_SInt => true,
            FGTextureFormat.RG32_Typeless => true,
            FGTextureFormat.RG32_Float => true,
            FGTextureFormat.RG32_UInt => true,
            FGTextureFormat.RG32_SInt => true,
            FGTextureFormat.RGB10A2_Typeless => true,
            FGTextureFormat.RGB10A2_UNorm => true,
            FGTextureFormat.RGB10A2_UInt => true,
            FGTextureFormat.RG11B10_Float => true,
            FGTextureFormat.RGBA8_Typeless => true,
            FGTextureFormat.RGBA8_UNorm => true,
            FGTextureFormat.RGBA8_UNorm_sRGB => true,
            FGTextureFormat.RGBA8_UInt => true,
            FGTextureFormat.RGBA8_SNorm => true,
            FGTextureFormat.RGBA8_SInt => true,
            FGTextureFormat.RG16_Typeless => true,
            FGTextureFormat.RG16_Float => true,
            FGTextureFormat.RG16_UNorm => true,
            FGTextureFormat.RG16_UInt => true,
            FGTextureFormat.RG16_SNorm => true,
            FGTextureFormat.RG16_SInt => true,
            FGTextureFormat.R32_Typeless => true,
            FGTextureFormat.R32_Float => true,
            FGTextureFormat.R32_UInt => true,
            FGTextureFormat.R32_SInt => true,
            FGTextureFormat.R8_Typeless => true,
            FGTextureFormat.R8_UNorm => true,
            FGTextureFormat.R8_UInt => true,
            FGTextureFormat.R8_SNorm => true,
            FGTextureFormat.R8_SInt => true,
            FGTextureFormat.A8_UNorm => true,
            FGTextureFormat.R16_Typeless => true,
            FGTextureFormat.R16_Float => true,
            FGTextureFormat.R16_UNorm => true,
            FGTextureFormat.R16_UInt => true,
            FGTextureFormat.R16_SNorm => true,
            FGTextureFormat.R16_SInt => true,
            FGTextureFormat.RG8_UNorm => true,
            FGTextureFormat.RG8_UInt => true,
            FGTextureFormat.RG8_SNorm => true,
            FGTextureFormat.RG8_SInt => true,
            _ => false
        };

        public static bool IsTexture2DFormat(this FGTextureFormat format) => format switch
        {
            FGTextureFormat.RGBA32_Typeless => true,
            FGTextureFormat.RGBA32_Float => true,
            FGTextureFormat.RGBA32_UInt => true,
            FGTextureFormat.RGBA32_SInt => true,
            FGTextureFormat.RGB32_Typeless => true,
            FGTextureFormat.RGB32_Float => true,
            FGTextureFormat.RGB32_UInt => true,
            FGTextureFormat.RGB32_SInt => true,
            FGTextureFormat.RGBA16_Typeless => true,
            FGTextureFormat.RGBA16_Float => true,
            FGTextureFormat.RGBA16_UInt => true,
            FGTextureFormat.RGBA16_SInt => true,
            FGTextureFormat.RG32_Typeless => true,
            FGTextureFormat.RG32_Float => true,
            FGTextureFormat.RG32_UInt => true,
            FGTextureFormat.RG32_SInt => true,
            FGTextureFormat.RGB10A2_Typeless => true,
            FGTextureFormat.RGB10A2_UNorm => true,
            FGTextureFormat.RGB10A2_UInt => true,
            FGTextureFormat.RG11B10_Float => true,
            FGTextureFormat.RGBA8_Typeless => true,
            FGTextureFormat.RGBA8_UNorm => true,
            FGTextureFormat.RGBA8_UNorm_sRGB => true,
            FGTextureFormat.RGBA8_UInt => true,
            FGTextureFormat.RGBA8_SNorm => true,
            FGTextureFormat.RGBA8_SInt => true,
            FGTextureFormat.RG16_Typeless => true,
            FGTextureFormat.RG16_Float => true,
            FGTextureFormat.RG16_UNorm => true,
            FGTextureFormat.RG16_UInt => true,
            FGTextureFormat.RG16_SNorm => true,
            FGTextureFormat.RG16_SInt => true,
            FGTextureFormat.R32_Typeless => true,
            FGTextureFormat.R32_Float => true,
            FGTextureFormat.R32_UInt => true,
            FGTextureFormat.R32_SInt => true,
            FGTextureFormat.R8_Typeless => true,
            FGTextureFormat.R8_UNorm => true,
            FGTextureFormat.R8_UInt => true,
            FGTextureFormat.R8_SNorm => true,
            FGTextureFormat.R8_SInt => true,
            FGTextureFormat.A8_UNorm => true,
            FGTextureFormat.R16_Typeless => true,
            FGTextureFormat.R16_Float => true,
            FGTextureFormat.R16_UNorm => true,
            FGTextureFormat.R16_UInt => true,
            FGTextureFormat.R16_SNorm => true,
            FGTextureFormat.R16_SInt => true,
            FGTextureFormat.RG8_UNorm => true,
            FGTextureFormat.RG8_UInt => true,
            FGTextureFormat.RG8_SNorm => true,
            FGTextureFormat.RG8_SInt => true,
            FGTextureFormat.BC1_Typeless => true,
            FGTextureFormat.BC1_UNorm => true,
            FGTextureFormat.BC1_Unorm_sRGB => true,
            FGTextureFormat.BC2_Typeless => true,
            FGTextureFormat.BC2_UNorm => true,
            FGTextureFormat.BC2_UNorm_sRGB => true,
            FGTextureFormat.BC3_Typeless => true,
            FGTextureFormat.BC3_UNorm => true,
            FGTextureFormat.BC3_UNorm_sRGB => true,
            FGTextureFormat.BC4_Typeless => true,
            FGTextureFormat.BC4_UNorm => true,
            FGTextureFormat.BC4_SNorm => true,
            FGTextureFormat.BC5_Typeless => true,
            FGTextureFormat.BC5_UNorm => true,
            FGTextureFormat.BC5_SNorm => true,
            FGTextureFormat.BC6H_Typeless => true,
            FGTextureFormat.BC5H_UFloat16 => true,
            FGTextureFormat.BC5H_SFloat16 => true,
            FGTextureFormat.BC7_Typeless => true,
            FGTextureFormat.BC7_UNorm => true,
            _ => false
        };

        public static bool IsTexture3DFormat(this FGTextureFormat format) => format switch
        {
            FGTextureFormat.RGBA32_Typeless => true,
            FGTextureFormat.RGBA32_Float => true,
            FGTextureFormat.RGBA32_UInt => true,
            FGTextureFormat.RGBA32_SInt => true,
            FGTextureFormat.RGB32_Typeless => true,
            FGTextureFormat.RGB32_Float => true,
            FGTextureFormat.RGB32_UInt => true,
            FGTextureFormat.RGB32_SInt => true,
            FGTextureFormat.RGBA16_Typeless => true,
            FGTextureFormat.RGBA16_Float => true,
            FGTextureFormat.RGBA16_UInt => true,
            FGTextureFormat.RGBA16_SInt => true,
            FGTextureFormat.RG32_Typeless => true,
            FGTextureFormat.RG32_Float => true,
            FGTextureFormat.RG32_UInt => true,
            FGTextureFormat.RG32_SInt => true,
            FGTextureFormat.RGB10A2_Typeless => true,
            FGTextureFormat.RGB10A2_UNorm => true,
            FGTextureFormat.RGB10A2_UInt => true,
            FGTextureFormat.RG11B10_Float => true,
            FGTextureFormat.RGBA8_Typeless => true,
            FGTextureFormat.RGBA8_UNorm => true,
            FGTextureFormat.RGBA8_UNorm_sRGB => true,
            FGTextureFormat.RGBA8_UInt => true,
            FGTextureFormat.RGBA8_SNorm => true,
            FGTextureFormat.RGBA8_SInt => true,
            FGTextureFormat.RG16_Typeless => true,
            FGTextureFormat.RG16_Float => true,
            FGTextureFormat.RG16_UNorm => true,
            FGTextureFormat.RG16_UInt => true,
            FGTextureFormat.RG16_SNorm => true,
            FGTextureFormat.RG16_SInt => true,
            FGTextureFormat.R32_Typeless => true,
            FGTextureFormat.R32_Float => true,
            FGTextureFormat.R32_UInt => true,
            FGTextureFormat.R32_SInt => true,
            FGTextureFormat.R8_Typeless => true,
            FGTextureFormat.R8_UNorm => true,
            FGTextureFormat.R8_UInt => true,
            FGTextureFormat.R8_SNorm => true,
            FGTextureFormat.R8_SInt => true,
            FGTextureFormat.A8_UNorm => true,
            FGTextureFormat.R16_Typeless => true,
            FGTextureFormat.R16_Float => true,
            FGTextureFormat.R16_UNorm => true,
            FGTextureFormat.R16_UInt => true,
            FGTextureFormat.R16_SNorm => true,
            FGTextureFormat.R16_SInt => true,
            FGTextureFormat.RG8_UNorm => true,
            FGTextureFormat.RG8_UInt => true,
            FGTextureFormat.RG8_SNorm => true,
            FGTextureFormat.RG8_SInt => true,
            FGTextureFormat.BC1_Typeless => true,
            FGTextureFormat.BC1_UNorm => true,
            FGTextureFormat.BC1_Unorm_sRGB => true,
            FGTextureFormat.BC2_Typeless => true,
            FGTextureFormat.BC2_UNorm => true,
            FGTextureFormat.BC2_UNorm_sRGB => true,
            FGTextureFormat.BC3_Typeless => true,
            FGTextureFormat.BC3_UNorm => true,
            FGTextureFormat.BC3_UNorm_sRGB => true,
            FGTextureFormat.BC4_Typeless => true,
            FGTextureFormat.BC4_UNorm => true,
            FGTextureFormat.BC4_SNorm => true,
            FGTextureFormat.BC5_Typeless => true,
            FGTextureFormat.BC5_UNorm => true,
            FGTextureFormat.BC5_SNorm => true,
            FGTextureFormat.BC6H_Typeless => true,
            FGTextureFormat.BC5H_UFloat16 => true,
            FGTextureFormat.BC5H_SFloat16 => true,
            FGTextureFormat.BC7_Typeless => true,
            FGTextureFormat.BC7_UNorm => true,
            _ => false
        };

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool IsTextureFormat(this FGTextureFormat format, FGTextureDimension dimension) => dimension switch
        {
            FGTextureDimension._1D => format.IsTexture1DFormat(),
            FGTextureDimension._2D => format.IsTexture2DFormat(),
            FGTextureDimension._3D => format.IsTexture3DFormat(),
            _ => false
        };

        public static bool IsRenderFormat(this FGTextureFormat format) => format switch
        {
            FGTextureFormat.RGBA32_Float => true,
            FGTextureFormat.RGBA32_UInt => true,
            FGTextureFormat.RGBA32_SInt => true,
            FGTextureFormat.RGB32_Float => true,
            FGTextureFormat.RGB32_UInt => true,
            FGTextureFormat.RGB32_SInt => true,
            FGTextureFormat.RGBA16_Float => true,
            FGTextureFormat.RGBA16_UInt => true,
            FGTextureFormat.RGBA16_SInt => true,
            FGTextureFormat.RG32_Float => true,
            FGTextureFormat.RG32_UInt => true,
            FGTextureFormat.RG32_SInt => true,
            FGTextureFormat.RGB10A2_UInt => true,
            FGTextureFormat.RGB10A2_UNorm => true,
            FGTextureFormat.RG11B10_Float => true,
            FGTextureFormat.RGBA8_UNorm => true,
            FGTextureFormat.RGBA8_UNorm_sRGB => true,
            FGTextureFormat.RGBA8_UInt => true,
            FGTextureFormat.RGBA8_SNorm => true,
            FGTextureFormat.RGBA8_SInt => true,
            FGTextureFormat.RG16_Float => true,
            FGTextureFormat.RG16_UNorm => true,
            FGTextureFormat.RG16_UInt => true,
            FGTextureFormat.RG16_SNorm => true,
            FGTextureFormat.RG16_SInt => true,
            FGTextureFormat.R32_Float => true,
            FGTextureFormat.R32_UInt => true,
            FGTextureFormat.R32_SInt => true,
            FGTextureFormat.RG8_UNorm => true,
            FGTextureFormat.RG8_UInt => true,
            FGTextureFormat.RG8_SNorm => true,
            FGTextureFormat.RG8_SInt => true,
            FGTextureFormat.R16_Float => true,
            FGTextureFormat.R16_UNorm => true,
            FGTextureFormat.R16_UInt => true,
            FGTextureFormat.R16_SNorm => true,
            FGTextureFormat.R16_SInt => true,
            FGTextureFormat.R8_UNorm => true,
            FGTextureFormat.R8_UInt => true,
            FGTextureFormat.R8_SNorm => true,
            FGTextureFormat.R8_SInt => true,
            FGTextureFormat.A8_UNorm => true,
            _ => false
        };

        public static bool IsDepthFormat(this FGTextureFormat format) => format switch
        {
            FGTextureFormat.D32_Float_S8X24_UInt => true,
            FGTextureFormat.D32_Float => true,
            FGTextureFormat.D24_UNorm_S8_UInt => true,
            FGTextureFormat.D16_UNorm => true,
            FGTextureFormat.R32_Float_X8X24_Typeless => true,
            FGTextureFormat.R32_Float => true,
            FGTextureFormat.R24G8_Typeless => true,
            FGTextureFormat.R16_UNorm => true,
            _ => false
        };
    }
}
