namespace Primary.Interop
{
    public enum ALLOCATOR_FLAGS
    {
        ALLOCATOR_FLAG_NONE = 0,
        ALLOCATOR_FLAG_SINGLETHREADED = 0x1,
        ALLOCATOR_FLAG_ALWAYS_COMMITTED = 0x2,
        ALLOCATOR_FLAG_DEFAULT_POOLS_NOT_ZEROED = 0x4,
        ALLOCATOR_FLAG_MSAA_TEXTURES_ALWAYS_COMMITTED = 0x8,
        ALLOCATOR_FLAG_DONT_PREFER_SMALL_BUFFERS_COMMITTED = 0x10,
    }
}
