namespace Primary.Interop
{
    public enum DEFRAGMENTATION_FLAGS
    {
        DEFRAGMENTATION_FLAG_ALGORITHM_FAST = 0x1,
        DEFRAGMENTATION_FLAG_ALGORITHM_BALANCED = 0x2,
        DEFRAGMENTATION_FLAG_ALGORITHM_FULL = 0x4,
        DEFRAGMENTATION_FLAG_ALGORITHM_MASK = DEFRAGMENTATION_FLAG_ALGORITHM_FAST | DEFRAGMENTATION_FLAG_ALGORITHM_BALANCED | DEFRAGMENTATION_FLAG_ALGORITHM_FULL,
    }
}
