namespace Primary.Interop
{
    public enum DEFRAGMENTATION_MOVE_OPERATION
    {
        DEFRAGMENTATION_MOVE_OPERATION_COPY = 0,
        DEFRAGMENTATION_MOVE_OPERATION_IGNORE = 1,
        DEFRAGMENTATION_MOVE_OPERATION_DESTROY = 2,
    }
}
