fill_mode = "Solid"
cull_mode = "None"
front_counter_clockwise = false
depth_bias = 0
depth_bias_clamp = 0.0
slope_scaled_depth_bias = 0.0
depth_clip_enable = true
conservative_raster = false
depth_enable = true
depth_write_mask = "None"
depth_func = "LessEqual"
stencil_enable = true
stencil_read_mask = 255
stencil_write_mask = 255
primitive_topology = "Triangle"
alpha_to_coverage_enable = false
independent_blend_enable = false
logic_op_enable = false
logic_op = "NoOp"
[front_face]
stencil_fail_op = "Keep"
stencil_depth_fail_op = "Keep"
stencil_pass_op = "Replace"
stencil_func = "Always"
[back_face]
stencil_fail_op = "Keep"
stencil_depth_fail_op = "Keep"
stencil_pass_op = "Replace"
stencil_func = "Always"
