using System;
using System.Collections.Generic;
using System.Text;

namespace Primary.RHI2
{
    public static class FormatHelper
    {
        public static bool IsShaderCapable(this RHIFormat format) => format switch
        {
            RHIFormat.RGBA32_Float => true,
            RHIFormat.RGBA32_UInt => true,
            RHIFormat.RGBA32_SInt => true,
            RHIFormat.RGB32_Float => true,
            RHIFormat.RGB32_UInt => true,
            RHIFormat.RGB32_SInt => true,
            RHIFormat.RG32_Float => true,
            RHIFormat.RG32_UInt => true,
            RHIFormat.RG32_SInt => true,
            RHIFormat.R32_Float => true,
            RHIFormat.R32_UInt => true,
            RHIFormat.R32_SInt => true,
            RHIFormat.RGBA16_Float => true,
            RHIFormat.RGBA16_UNorm => true,
            RHIFormat.RGBA16_UInt => true,
            RHIFormat.RGBA16_SNorm => true,
            RHIFormat.RGBA16_SInt => true,
            RHIFormat.RG16_Float => true,
            RHIFormat.RG16_UNorm => true,
            RHIFormat.RG16_UInt => true,
            RHIFormat.RG16_SNorm => true,
            RHIFormat.RG16_SInt => true,
            RHIFormat.R16_Float => true,
            RHIFormat.R16_UInt => true,
            RHIFormat.R16_SNorm => true,
            RHIFormat.R16_SInt => true,
            RHIFormat.RGBA8_UNorm => true,
            RHIFormat.RGBA8_UNorm_sRGB => true,
            RHIFormat.RGBA8_UInt => true,
            RHIFormat.RGBA8_SNorm => true,
            RHIFormat.RGBA8_SInt => true,
            RHIFormat.RG8_UNorm => true,
            RHIFormat.RG8_UInt => true,
            RHIFormat.RG8_SNorm => true,
            RHIFormat.RG8_SInt => true,
            RHIFormat.R8_UNorm => true,
            RHIFormat.R8_UInt => true,
            RHIFormat.R8_SNorm => true,
            RHIFormat.R8_SInt => true,
            RHIFormat.RGB10A2_Typeless => true,
            RHIFormat.RGB10A2_UNorm => true,
            RHIFormat.RGB10A2_UInt => true,
            RHIFormat.RG11B10_Float => true,
            RHIFormat.R32G8X24_Typeless => true,
            RHIFormat.R32_Float_X8X24_Typeless => true,
            RHIFormat.X32_Typeless_G8X24_UInt => true,
            RHIFormat.R24G8_Typeless => true,
            RHIFormat.R24_UNorm_X8_Typeless => true,
            RHIFormat.X24_Typeless_G8_UInt => true,
            RHIFormat.BC1_Typeless => true,
            RHIFormat.BC1_UNorm => true,
            RHIFormat.BC1_UNorm_sRGB => true,
            RHIFormat.BC2_Typeless => true,
            RHIFormat.BC2_UNorm => true,
            RHIFormat.BC2_UNorm_sRGB => true,
            RHIFormat.BC3_Typeless => true,
            RHIFormat.BC3_UNorm => true,
            RHIFormat.BC3_UNorm_sRGB => true,
            RHIFormat.BC4_Typeless => true,
            RHIFormat.BC4_UNorm => true,
            RHIFormat.BC4_SNorm => true,
            RHIFormat.BC5_Typeless => true,
            RHIFormat.BC5_UNorm => true,
            RHIFormat.BC5_SNorm => true,
            RHIFormat.BC6H_Typeless => true,
            RHIFormat.BC6H_UFloat16 => true,
            RHIFormat.BC6H_SFloat16 => true,
            RHIFormat.BC7_Typeless => true,
            RHIFormat.BC7_UNorm => true,
            RHIFormat.BC7_UNorm_sRGB => true,
            _ => false,
        };

        public static bool IsRenderTargetCapable(this RHIFormat format) => format switch
        {
            RHIFormat.RGBA32_Float => true,
            RHIFormat.RGBA32_UInt => true,
            RHIFormat.RGBA32_SInt => true,
            RHIFormat.RGB32_Float => true,
            RHIFormat.RGB32_UInt => true,
            RHIFormat.RGB32_SInt => true,
            RHIFormat.RG32_Float => true,
            RHIFormat.RG32_UInt => true,
            RHIFormat.RG32_SInt => true,
            RHIFormat.R32_Float => true,
            RHIFormat.R32_UInt => true,
            RHIFormat.R32_SInt => true,
            RHIFormat.RGBA16_Typeless => true,
            RHIFormat.RGBA16_Float => true,
            RHIFormat.RGBA16_UNorm => true,
            RHIFormat.RGBA16_UInt => true,
            RHIFormat.RGBA16_SNorm => true,
            RHIFormat.RGBA16_SInt => true,
            RHIFormat.RG16_Typeless => true,
            RHIFormat.RG16_Float => true,
            RHIFormat.RG16_UNorm => true,
            RHIFormat.RG16_UInt => true,
            RHIFormat.RG16_SNorm => true,
            RHIFormat.RG16_SInt => true,
            RHIFormat.R16_Typeless => true,
            RHIFormat.R16_Float => true,
            RHIFormat.R16_UInt => true,
            RHIFormat.R16_SNorm => true,
            RHIFormat.R16_SInt => true,
            RHIFormat.RGBA8_Typeless => true,
            RHIFormat.RGBA8_UNorm => true,
            RHIFormat.RGBA8_UNorm_sRGB => true,
            RHIFormat.RGBA8_UInt => true,
            RHIFormat.RGBA8_SNorm => true,
            RHIFormat.RGBA8_SInt => true,
            RHIFormat.RG8_Typeless => true,
            RHIFormat.RG8_UNorm => true,
            RHIFormat.RG8_UInt => true,
            RHIFormat.RG8_SNorm => true,
            RHIFormat.RG8_SInt => true,
            RHIFormat.R8_Typeless => true,
            RHIFormat.R8_UNorm => true,
            RHIFormat.R8_UInt => true,
            RHIFormat.R8_SNorm => true,
            RHIFormat.R8_SInt => true,
            RHIFormat.RGB10A2_Typeless => true,
            RHIFormat.RGB10A2_UNorm => true,
            RHIFormat.RGB10A2_UInt => true,
            RHIFormat.RG11B10_Float => true,
            _ => false,
        };

        public static bool IsDepthStencilCapable(this RHIFormat format) => format switch
        {
            RHIFormat.R32_Typeless => true,
            RHIFormat.R16_Typeless => true,
            RHIFormat.D32_Float => true,
            RHIFormat.D16_UNorm => true,
            RHIFormat.R32G8X24_Typeless => true,
            RHIFormat.D32_Float_S8X24_UInt => true,
            RHIFormat.R32_Float_X8X24_Typeless => true,
            RHIFormat.X32_Typeless_G8X24_UInt => true,
            RHIFormat.R24G8_Typeless => true,
            RHIFormat.D24_UNorm_S8_UInt => true,
            RHIFormat.R24_UNorm_X8_Typeless => true,
            RHIFormat.X24_Typeless_G8_UInt => true,
            _ => false,
        };
    }
}
