namespace Interop.D3D12MemAlloc
{
    public enum ALLOCATION_FLAGS
    {
        ALLOCATION_FLAG_NONE = 0,
        ALLOCATION_FLAG_COMMITTED = 0x1,
        ALLOCATION_FLAG_NEVER_ALLOCATE = 0x2,
        ALLOCATION_FLAG_WITHIN_BUDGET = 0x4,
        ALLOCATION_FLAG_UPPER_ADDRESS = 0x8,
        ALLOCATION_FLAG_CAN_ALIAS = 0x10,
        ALLOCATION_FLAG_STRATEGY_MIN_MEMORY = 0x00010000,
        ALLOCATION_FLAG_STRATEGY_MIN_TIME = 0x00020000,
        ALLOCATION_FLAG_STRATEGY_MIN_OFFSET = 0x0004000,
        ALLOCATION_FLAG_STRATEGY_BEST_FIT = ALLOCATION_FLAG_STRATEGY_MIN_MEMORY,
        ALLOCATION_FLAG_STRATEGY_FIRST_FIT = ALLOCATION_FLAG_STRATEGY_MIN_TIME,
        ALLOCATION_FLAG_STRATEGY_MASK = ALLOCATION_FLAG_STRATEGY_MIN_MEMORY | ALLOCATION_FLAG_STRATEGY_MIN_TIME | ALLOCATION_FLAG_STRATEGY_MIN_OFFSET,
    }
}
