using static Interop.D3D12MemAlloc.POOL_FLAGS;

namespace Interop.D3D12MemAlloc
{
    public enum VIRTUAL_BLOCK_FLAGS
    {
        VIRTUAL_BLOCK_FLAG_NONE = 0,
        VIRTUAL_BLOCK_FLAG_ALGORITHM_LINEAR = POOL_FLAG_ALGORITHM_LINEAR,
        VIRTUAL_BLOCK_FLAG_ALGORITHM_MASK = POOL_FLAG_ALGORITHM_MASK,
    }
}
