flip_vertical = false
image_format = "BC7"
cutout_dither = false
cutout_threshold = 127
gamma_correct = false
premultiplied_alpha = false
mipmap_filter = "Box"
max_mipmap_count = 2147483647
min_mipmap_size = 1
generate_mipmaps = false
image_type = "Colormap"
scale_alpha_for_mipmaps = false