<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<FileVersion>1.0.1369.0</FileVersion>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Assets\Importers\StylesheetImporter.cs" />
	  <Compile Remove="Assets\Importers\UIFontFamilyImporter.cs" />
	  <Compile Remove="Assets\Importers\UILayoutImporter.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Editor.Shaders\Editor.Shaders.csproj" />
		<ProjectReference Include="..\EditorUI\EditorUI.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Arguments.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Filesystems.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SplashData.bundle">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Primary.SourceGenerator\Primary.SourceGenerator.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Silk.NET.Assimp" Version="2.23.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Rendering\Passes\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Assets\Importers\StylesheetImporter.cs" />
	  <None Include="Assets\Importers\UIFontFamilyImporter.cs" />
	  <None Include="Assets\Importers\UILayoutImporter.cs" />
	</ItemGroup>
	
	<Target Name="PatchExec" AfterTargets="PostBuildEvent">
		<Exec Command="call &quot;..\..\..\..\..\Patcher\D3D12SDKVersionPatcher\PatchEditor.bat&quot; &quot;PrimaryEditor&quot;" WorkingDirectory="$(OutDir)" />
	</Target>
	
	<ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>

</Project>
