<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Configurations>Debug;Release;ReleaseWithDebug</Configurations>
		<FileVersion>1.0.60.0</FileVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseWithDebug|AnyCPU'">
		<DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
		<Optimize>True</Optimize>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Vortice.Direct3D12" Version="3.8.3" />
	</ItemGroup>
	<ItemGroup>
		<None Update="runtimes\win-arm64\native\WinPixEventRuntime.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="runtimes\win-x64\native\WinPixEventRuntime.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>