namespace Primary.RHI
{
    public enum RenderTargetFormat : byte
    {
        Undefined = 0,
        RGBA32sf,
        RGBA32ui,
        RGBA32si,
        RGB32sf,
        RGB32ui,
        RGB32si,
        RGBA16sf,
        RGBA16un,
        RGBA16ui,
        RGBA16sn,
        RGBA16si,
        RG32sf,
        RG32ui,
        RG32si,
        RGB10A2un,
        RGB10A2ui,
        RG11B10sf,
        RGBA8un,
        RGBA8un_sRGB,
        RGBA8ui,
        RGBA8sn,
        RGBA8si,
        RG16sf,
        RG16un,
        RG16ui,
        RG16sn,
        RG16si,
        R32sf,
        R32ui,
        R32si,
        RG8un,
        RG8ui,
        RG8sn,
        RG8si,
        R16sf,
        R16un,
        R16ui,
        R16sn,
        R16si,
        R8un,
        R8ui,
        R8sn,
        R8si,
        A8un,
        B5G6R6un,
        BGR5A1un,
        BGRA8un,
        BGRA8un_sRGB,
        BGRX8un,
        BGRX8un_sRGB,
    }

    public enum DepthStencilFormat : byte
    {
        Undefined = 0,
        D32sfS8X24ui,
        D32sf,
        D24unS8ui,
        D16un,
        R32t
    }
}
